server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_teste
    username: root
    password: senha123
  jpa:
    show-sql: false # exibir SQL utilizado
    hibernate:
      ddl-auto: update # sempre atualiza o db conforme dados do projeto -> marcar false quando for para prod com flyway
